[project]
name = "ProctorAI"
version = "0.1.0"
description = "Add a short description here"
authors = ["James Campbell <campbellj@optonline.net>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
wcwidth = "==0.2.13"
portaudio = ">=19.6.0,<19.7"
black = ">=24.4.2,<24.5"

[pypi-dependencies]
grpcio = "==1.64.0"
altgraph = "==0.17.4"
annotated-types = "==0.6.0"
anthropic = "==0.29.0"
anyio = "==4.3.0"
appnope = "==0.1.4"
asttokens = "==2.4.1"
cachetools = "==5.3.3"
certifi = "==2024.2.2"
cffi = "==1.16.0"
charset-normalizer = "==3.3.2"
comm = "==0.2.2"
contourpy = "==1.2.1"
cycler = "==0.12.1"
debugpy = "==1.8.1"
decorator = "==5.1.1"
distro = "==1.9.0"
executing = "==2.0.1"
filelock = "==3.15.3"
fonttools = "==4.51.0"
fsspec = "==2024.6.0"
google-ai-generativelanguage = "==0.6.4"
google-api-core = "==2.19.0"
google-api-python-client = "==2.131.0"
google-auth = "==2.29.0"
google-auth-httplib2 = "==0.2.0"
google-generativeai = "==0.5.4"
googleapis-common-protos = "==1.63.0"
grpcio-status = "==1.62.2"
h11 = "==0.14.0"
httpcore = "==1.0.5"
httplib2 = "==0.22.0"
httpx = "==0.27.0"
huggingface-hub = "==0.23.4"
idna = "==3.7"
ipykernel = "==6.29.4"
ipython = "==8.24.0"
jedi = "==0.19.1"
jiter = "==0.4.2"
jupyter-client = "==8.6.1"
jupyter-core = "==5.7.2"
keyboard = "==0.13.5"
kiwisolver = "==1.4.5"
macholib = "==1.16.3"
matplotlib = "==3.9.0"
matplotlib-inline = "==0.1.7"
nest-asyncio = "==1.6.0"
numpy = "==1.26.4"
openai = "==1.30.1"
opencv-python = "==4.9.0.80"
parso = "==0.8.4"
pexpect = "==4.9.0"
pillow = "==10.3.0"
platformdirs = "==4.2.2"
prompt-toolkit = "==3.0.43"
proto-plus = "==1.23.0"
protobuf = "==4.25.3"
psutil = "==5.9.8"
ptyprocess = "==0.7.0"
pure-eval = "==0.2.2"
pyasn1 = "==0.6.0"
pyasn1-modules = "==0.4.0"
pycparser = "==2.22"
pydantic = "==2.7.1"
pydantic-core = "==2.18.2"
pydub = "==0.25.1"
pygame = "==2.5.2"
pygments = "==2.18.0"
pyinstaller = "==6.9.0"
pyinstaller-hooks-contrib = "==2024.7"
pynput = "==1.7.7"
pyobjc = "==10.2"
pyobjc-core = "==10.2"
pyobjc-framework-accessibility = "==10.2"
pyobjc-framework-accounts = "==10.2"
pyobjc-framework-addressbook = "==10.2"
pyobjc-framework-adservices = "==10.2"
pyobjc-framework-adsupport = "==10.2"
pyobjc-framework-applescriptkit = "==10.2"
pyobjc-framework-applescriptobjc = "==10.2"
pyobjc-framework-applicationservices = "==10.2"
pyobjc-framework-apptrackingtransparency = "==10.2"
pyobjc-framework-audiovideobridging = "==10.2"
pyobjc-framework-authenticationservices = "==10.2"
pyobjc-framework-automaticassessmentconfiguration = "==10.2"
pyobjc-framework-automator = "==10.2"
pyobjc-framework-avfoundation = "==10.2"
pyobjc-framework-avkit = "==10.2"
pyobjc-framework-avrouting = "==10.2"
pyobjc-framework-backgroundassets = "==10.2"
pyobjc-framework-businesschat = "==10.2"
pyobjc-framework-calendarstore = "==10.2"
pyobjc-framework-callkit = "==10.2"
pyobjc-framework-cfnetwork = "==10.2"
pyobjc-framework-cinematic = "==10.2"
pyobjc-framework-classkit = "==10.2"
pyobjc-framework-cloudkit = "==10.2"
pyobjc-framework-cocoa = "==10.2"
pyobjc-framework-collaboration = "==10.2"
pyobjc-framework-colorsync = "==10.2"
pyobjc-framework-contacts = "==10.2"
pyobjc-framework-contactsui = "==10.2"
pyobjc-framework-coreaudio = "==10.2"
pyobjc-framework-coreaudiokit = "==10.2"
pyobjc-framework-corebluetooth = "==10.2"
pyobjc-framework-coredata = "==10.2"
pyobjc-framework-corehaptics = "==10.2"
pyobjc-framework-corelocation = "==10.2"
pyobjc-framework-coremedia = "==10.2"
pyobjc-framework-coremediaio = "==10.2"
pyobjc-framework-coremidi = "==10.2"
pyobjc-framework-coreml = "==10.2"
pyobjc-framework-coremotion = "==10.2"
pyobjc-framework-coreservices = "==10.2"
pyobjc-framework-corespotlight = "==10.2"
pyobjc-framework-coretext = "==10.2"
pyobjc-framework-corewlan = "==10.2"
pyobjc-framework-cryptotokenkit = "==10.2"
pyobjc-framework-datadetection = "==10.2"
pyobjc-framework-devicecheck = "==10.2"
pyobjc-framework-dictionaryservices = "==10.2"
pyobjc-framework-discrecording = "==10.2"
pyobjc-framework-discrecordingui = "==10.2"
pyobjc-framework-diskarbitration = "==10.2"
pyobjc-framework-dvdplayback = "==10.2"
pyobjc-framework-eventkit = "==10.2"
pyobjc-framework-exceptionhandling = "==10.2"
pyobjc-framework-executionpolicy = "==10.2"
pyobjc-framework-extensionkit = "==10.2"
pyobjc-framework-externalaccessory = "==10.2"
pyobjc-framework-fileprovider = "==10.2"
pyobjc-framework-fileproviderui = "==10.2"
pyobjc-framework-findersync = "==10.2"
pyobjc-framework-fsevents = "==10.2"
pyobjc-framework-gamecenter = "==10.2"
pyobjc-framework-gamecontroller = "==10.2"
pyobjc-framework-gamekit = "==10.2"
pyobjc-framework-gameplaykit = "==10.2"
pyobjc-framework-healthkit = "==10.2"
pyobjc-framework-imagecapturecore = "==10.2"
pyobjc-framework-inputmethodkit = "==10.2"
pyobjc-framework-installerplugins = "==10.2"
pyobjc-framework-instantmessage = "==10.2"
pyobjc-framework-intents = "==10.2"
pyobjc-framework-intentsui = "==10.2"
pyobjc-framework-iobluetooth = "==10.2"
pyobjc-framework-iobluetoothui = "==10.2"
pyobjc-framework-iosurface = "==10.2"
pyobjc-framework-ituneslibrary = "==10.2"
pyobjc-framework-kernelmanagement = "==10.2"
pyobjc-framework-latentsemanticmapping = "==10.2"
pyobjc-framework-launchservices = "==10.2"
pyobjc-framework-libdispatch = "==10.2"
pyobjc-framework-libxpc = "==10.2"
pyobjc-framework-linkpresentation = "==10.2"
pyobjc-framework-localauthentication = "==10.2"
pyobjc-framework-localauthenticationembeddedui = "==10.2"
pyobjc-framework-mailkit = "==10.2"
pyobjc-framework-mapkit = "==10.2"
pyobjc-framework-mediaaccessibility = "==10.2"
pyobjc-framework-medialibrary = "==10.2"
pyobjc-framework-mediaplayer = "==10.2"
pyobjc-framework-mediatoolbox = "==10.2"
pyobjc-framework-metal = "==10.2"
pyobjc-framework-metalfx = "==10.2"
pyobjc-framework-metalkit = "==10.2"
pyobjc-framework-metalperformanceshaders = "==10.2"
pyobjc-framework-metalperformanceshadersgraph = "==10.2"
pyobjc-framework-metrickit = "==10.2"
pyobjc-framework-mlcompute = "==10.2"
pyobjc-framework-modelio = "==10.2"
pyobjc-framework-multipeerconnectivity = "==10.2"
pyobjc-framework-naturallanguage = "==10.2"
pyobjc-framework-netfs = "==10.2"
pyobjc-framework-network = "==10.2"
pyobjc-framework-networkextension = "==10.2"
pyobjc-framework-notificationcenter = "==10.2"
pyobjc-framework-opendirectory = "==10.2"
pyobjc-framework-osakit = "==10.2"
pyobjc-framework-oslog = "==10.2"
pyobjc-framework-passkit = "==10.2"
pyobjc-framework-pencilkit = "==10.2"
pyobjc-framework-phase = "==10.2"
pyobjc-framework-photos = "==10.2"
pyobjc-framework-photosui = "==10.2"
pyobjc-framework-preferencepanes = "==10.2"
pyobjc-framework-pushkit = "==10.2"
pyobjc-framework-quartz = "==10.2"
pyobjc-framework-quicklookthumbnailing = "==10.2"
pyobjc-framework-replaykit = "==10.2"
pyobjc-framework-safariservices = "==10.2"
pyobjc-framework-safetykit = "==10.2"
pyobjc-framework-scenekit = "==10.2"
pyobjc-framework-screencapturekit = "==10.2"
pyobjc-framework-screensaver = "==10.2"
pyobjc-framework-screentime = "==10.2"
pyobjc-framework-scriptingbridge = "==10.2"
pyobjc-framework-searchkit = "==10.2"
pyobjc-framework-security = "==10.2"
pyobjc-framework-securityfoundation = "==10.2"
pyobjc-framework-securityinterface = "==10.2"
pyobjc-framework-sensitivecontentanalysis = "==10.2"
pyobjc-framework-servicemanagement = "==10.2"
pyobjc-framework-sharedwithyou = "==10.2"
pyobjc-framework-sharedwithyoucore = "==10.2"
pyobjc-framework-shazamkit = "==10.2"
pyobjc-framework-social = "==10.2"
pyobjc-framework-soundanalysis = "==10.2"
pyobjc-framework-speech = "==10.2"
pyobjc-framework-spritekit = "==10.2"
pyobjc-framework-storekit = "==10.2"
pyobjc-framework-symbols = "==10.2"
pyobjc-framework-syncservices = "==10.2"
pyobjc-framework-systemconfiguration = "==10.2"
pyobjc-framework-systemextensions = "==10.2"
pyobjc-framework-threadnetwork = "==10.2"
pyobjc-framework-uniformtypeidentifiers = "==10.2"
pyobjc-framework-usernotifications = "==10.2"
pyobjc-framework-usernotificationsui = "==10.2"
pyobjc-framework-videosubscriberaccount = "==10.2"
pyobjc-framework-videotoolbox = "==10.2"
pyobjc-framework-virtualization = "==10.2"
pyobjc-framework-vision = "==10.2"
pyobjc-framework-webkit = "==10.2"
pyparsing = "==3.1.2"
pyqt5 = "==5.15.10"
pyqt5-qt5 = "==5.15.14"
pyqt5-sip = "==12.13.0"
python-dateutil = "==2.9.0.post0"
pyttsx3 = "==2.90"
pyyaml = "==6.0.1"
pyzmq = "==26.0.3"
regex = "==2024.5.15"
requests = "==2.31.0"
rsa = "==4.9"
setuptools = "==70.2.0"
six = "==1.16.0"
sniffio = "==1.3.1"
sounddevice = "==0.4.7"
soundfile = "==0.12.1"
stack-data = "==0.6.3"
tiktoken = "==0.7.0"
tk = "==0.1.0"
tokenizers = "==0.19.1"
tornado = "==6.4"
tqdm = "==4.66.4"
traitlets = "==5.14.3"
typing-extensions = "==4.11.0"
uritemplate = "==4.1.1"
urllib3 = "==2.2.1"
wcwidth = "==0.2.13"
packaging = "*"
pyaudio = ">=0.2.14, <0.3"
